/**
 * Cloudflare Worker Entrypoint for Automata Constrained Sequence Synthesis (v5.0)
 * Serves static assets generated by Vite with Single Page Application (SPA) fallback routing.
 */

interface Env {
  ASSETS: {
    fetch: (request: Request | string) => Promise<Response>;
  };
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    try {
      // 1. Attempt to fetch static asset directly
      const response = await env.ASSETS.fetch(request);

      // If found, return response
      if (response.status !== 404) {
        return response;
      }

      // 2. SPA fallback for client-side navigation: serve root index.html
      const url = new URL(request.url);
      const indexRequest = new Request(new URL('/', url.origin), request);
      return await env.ASSETS.fetch(indexRequest);
    } catch {
      return new Response('Automata Synthesizer: Failed to load application assets.', {
        status: 500,
        headers: { 'content-type': 'text/plain; charset=utf-8' },
      });
    }
  },
};
